version: '3.2'
services:
  # local-registry:
  #   build:
  #     context: test-resources
  #     dockerfile: Dockerfile.registry
  #   ports:
  #     - '5000:5000'
  local-broker:
    build:
      context: test-resources
      dockerfile: Dockerfile.broker
    ports:
      - '15672:15672'
      - '5672:5672'