version: '3.2'
services:
  # local-registry:
  #   build:
  #     context: test-resources
  #     dockerfile: Dockerfile.registry
  #   ports:
  #     - '5000:5000'
  local-broker:
    build:
      context: test-resources
      dockerfile: Dockerfile.broker
    volumes:
      - ./local-dev/certificates/ca.crt:/ca.crt:ro
      - ./local-dev/certificates/tls.crt:/tls.crt:ro
      - ./local-dev/certificates/tls.key:/tls.key:ro
    ports:
      - '15672:15672'
      - '5671:5671'