name: dependency review
on:
  pull_request:
    branches:
    - main
permissions: {}
jobs:
  dependency-review:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709 # v4.2.2
    - uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
      with:
        config-file: .github/dependency-review-config.yaml
