name: Lagoon Storage Controller Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        kindest_node_version: [v1.29.14@sha256:8703bd94ee24e51b778d5556ae310c6c0fa67d761fae6379c8e0bb480e6fea29]
        experimental: [false]
        include:
          - kindest_node_version: v1.30.10@sha256:4de75d0e82481ea846c0ed1de86328d821c1e6a6a91ac37bf804e5313670e507
            experimental: false
          - kindest_node_version: v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
            experimental: false
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 1
      continue-on-error: true
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: "0"
    - name: Set up testing dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential && sudo apt-get clean
    - name: Setup correct Go version
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Create kind cluster
      uses: helm/kind-action@v1.12.0
      with:
        version: v0.27.0
        cluster_name: storage-calculator
        node_image: kindest/node:${{ matrix.kindest_node_version }}
        kubectl_version: v1.32.2
  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run test-e2e
      run: |
        make test-e2e KIND_NETWORK=kind