name: Lagoon Storage Controller Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        kindest_node_version: [v1.25.16, v1.26.15]
        experimental: [false]
        include:
          - kindest_node_version: v1.27.13
            experimental: false
          - kindest_node_version: v1.28.9
            experimental: false
          - kindest_node_version: v1.29.4
            experimental: true
          - kindest_node_version: v1.30.2
            experimental: true
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 1
      continue-on-error: true
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Set up testing dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential && sudo apt-get clean
    - name: Setup correct Go version
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'    

    - name: Create kind cluster
      uses: helm/kind-action@v1.10.0
      with:
        version: v0.24.0
        cluster_name: storage-calculator
        node_image: kindest/node:${{ matrix.kindest_node_version }}
        kubectl_version: v1.30.4
  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run test-e2e
      run: |
        make test-e2e